'use strict';
const $=id=>document.getElementById(id), token=location.hash.slice(1)||sessionStorage.getItem('astra.uiToken')||'';
if(token)sessionStorage.setItem('astra.uiToken',token);
history.replaceState(null,'',location.pathname);
const names={100:'소총',101:'총열',102:'소음기',103:'조준경',104:'탄창',105:'보통탄',106:'철갑탄',107:'개조 부품',108:'목재',109:'강철',110:'천',111:'붕대',112:'물',113:'식량',114:'공구',115:'설치물',116:'고철',117:'방탄복',118:'차체',119:'바퀴',120:'잔해',121:'엔진',122:'배터리',123:'차량 장갑',124:'연료'};
const errors=['완료','잘못된 명령','상호작용할 수 없습니다','월드가 재시작되었습니다','입력 순서가 맞지 않습니다','재시도 내용이 변경되었습니다','상태가 바뀌었습니다','수량을 확인하세요','배치할 수 없습니다','용량이 부족합니다','순환 지지/보관 관계','중첩 깊이 초과','상태 검사 실패','호환되지 않습니다','허용량을 초과했습니다','저장 확인 중 · 같은 명령을 재시도하세요','처리 중 · 같은 명령을 재시도하세요','저장할 수 없습니다 · 같은 명령을 재시도하세요'];
let state,selected,busy=false,viewBusy=false;
async function api(route,body={}){const response=await fetch(route,{method:'POST',headers:{'Authorization':'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!response.ok)throw Error('연결 또는 요청 오류');return response.json();}
async function act(command){if(busy)return;busy=true;try{const r=await api('/command',{command});$('message').textContent=errors[r.code]??'응답 오류';await refresh();return r;}catch(e){$('message').textContent=e.message;}finally{busy=false;}}
async function refresh(){if(viewBusy)return;viewBusy=true;try{const s=await api('/command',{command:'show'});if(s.code!==0)return;state=s;render();}catch(e){$('message').textContent=e.message;}finally{viewBusy=false;}}
function label(tag,text){const e=document.createElement(tag);e.textContent=text;return e;}
function button(text,action){const b=label('button',text);b.onclick=action;return b;}
function renderStores(){
 const prior=$('storage').value,stores=state.stores??[];$('storage').replaceChildren(...stores.map(s=>{const e=label('option',s.entity);e.value=s.container;return e;}));if(stores.some(s=>s.container===prior))$('storage').value=prior;
 $('stored-items').replaceChildren(...stores.flatMap(s=>s.items.map(i=>{const e=label('div',`${names[i.def]??i.def} × ${i.qty} · (${i.x}, ${i.y})`);e.className='entity';e.append(button('가져오기',()=>act(`put ${i.id} ${state.bag} ${i.qty} ${$('grid-x').value} ${$('grid-y').value} 0`)));return e;})));
}
$('stash').onclick=()=>{const i=state?.items.find(i=>i.id===selected);if(i&&$('storage').value)act(`put ${i.id} ${$('storage').value} ${i.qty} ${$('grid-x').value} ${$('grid-y').value} 0`);};
$('bandage').onclick=()=>{const bandage=state?.items.find(i=>i.def===111),wound=state?.wounds[0];if(bandage&&wound)act(`treat ${bandage.id} ${state.actor} ${wound.event}`);};
function render(){
 const status=['활동 가능','의식 없음','사망'][state.status];$('position').textContent=`${status} · ${state.position.map(x=>x.toFixed(1)).join(', ')}m`;
 $('hud').replaceChildren(...[['혈액',state.bloodMl.toFixed(0)+' ml'],['수분',state.waterMl.toFixed(0)+' ml'],['에너지',state.energyKcal.toFixed(0)+' kcal'],['체력',state.staminaJ.toFixed(0)+' J'],['체온',(state.coreK-273.15).toFixed(1)+' °C'],['생명 상태',status]].map(([name,value])=>{const e=label('div','');e.className='metric';e.append(label('span',name),label('strong',value));return e;}));
 $('inventory').replaceChildren(...state.items.map(i=>{const e=label('div','');e.className='item'+(i.id===selected?' selected':'');e.tabIndex=0;e.setAttribute('role','button');const n=label('div',names[i.def]??'물품 '+i.def);n.append(label('small',i.id+' · '+i.container));e.append(n,label('span','× '+i.qty));const choose=()=>{selected=i.id;render();};e.onclick=choose;e.onkeydown=x=>{if(x.key==='Enter')choose();};return e;}));
 const prior=$('station').value;const stations=state.nearby.filter(e=>e.kind==='station'&&e.capabilities);$('station').replaceChildren(...stations.map(e=>{const option=label('option',`T${Math.log2(e.capabilities)+1} · ${e.id}`);option.value=e.id;return option;}));if(stations.some(e=>e.id===prior))$('station').value=prior;
 $('jobs').replaceChildren(...state.jobs.filter(j=>j.phase!==5).map(j=>{const e=label('div',j.recipe+' · '+['진행','정지','수거 대기','취소','파괴','수거'][j.phase]);e.className='job';e.append(button(j.phase<2?'취소':'수거',()=>act(`${j.phase<2?'cancel':'collect'} ${j.id}`)));return e;}));
 $('nearby').replaceChildren(...state.nearby.slice(0,60).map(e=>{const n=label('div',`${e.kind} · ${e.id}`);n.className='entity';if(e.kind==='loot')n.append(button('줍기',()=>act('loot '+e.id+' 1')));if(e.kind==='vehicle'){n.append(button(state.vehicle===e.id?'하차':'탑승',()=>act((state.vehicle===e.id?'exit ':'enter ')+e.id)));n.append(button('급유',()=>act('refuel '+e.id+' 1')));}if(e.kind==='structure'){if(e.definition===14){n.append(button('문 열기',()=>act('door '+e.id+' 1')));n.append(button('문 닫기',()=>act('door '+e.id+' 0')));}n.append(button('지지 선택',()=>{$('support').value=e.id;}));}if(e.owned&&(e.definition===14||e.definition===17||e.definition===19))n.append(button(e.locked?'잠금 해제':'잠그기',()=>act(`lock ${e.id} ${Number(!e.locked)}`)));return n;}));renderStores();draw();
}
function draw(){const c=$('map'),g=c.getContext('2d'),scale=9;g.clearRect(0,0,c.width,c.height);g.strokeStyle='#294039';g.lineWidth=1;for(let x=0;x<c.width;x+=45){g.beginPath();g.moveTo(x,0);g.lineTo(x,c.height);g.stroke();}for(let y=0;y<c.height;y+=45){g.beginPath();g.moveTo(0,y);g.lineTo(c.width,y);g.stroke();}
 for(const e of state.nearby){const x=c.width/2+(e.position[0]-state.position[0])*scale,y=c.height/2-(e.position[1]-state.position[1])*scale;g.fillStyle=({zombie:'#dd855d',vehicle:'#8cbbb7',station:'#cabd82',structure:'#748d78',loot:'#d9bf7b',player:'#9dacd6'})[e.kind];g.fillRect(x-4,y-4,8,8);g.fillStyle='#95a99e';g.font='11px sans-serif';g.fillText(e.kind,x+8,y+4);}g.fillStyle='#d5ec9e';g.beginPath();g.arc(c.width/2,c.height/2,7,0,Math.PI*2);g.fill();g.fillText('나',c.width/2+12,c.height/2+4);}
const first=def=>state?.items.find(i=>i.def===def)?.id;
$('fire').onclick=()=>{const id=first(100);if(id)act('fire '+id);};$('reload').onclick=()=>{const gun=first(100),mag=state?.items.find(i=>i.def===104&&i.container===state.bag);if(gun&&mag)act(`reload ${gun} ${mag.id}`);};$('drink').onclick=()=>{const id=first(112);if(id)act('consume '+id);};$('eat').onclick=()=>{const id=first(113);if(id)act('consume '+id);};$('respawn').onclick=()=>act('respawn');$('equip').onclick=()=>selected&&act('equip '+selected+' 1');$('drop').onclick=()=>{const i=state?.items.find(i=>i.id===selected);if(i)act(`drop ${i.id} ${i.qty}`);};$('craft').onclick=()=>act(`craft ${$('station').value} ${$('recipe').value} 1`);
$('build').onclick=()=>{if(!state)return;const def=Number($('building').value),support=state.nearby.find(e=>e.id===$('support').value),z=def===10?.1:(support?.position[2]??.1)+(def>=17?.45:1.1);act(`build ${def} ${(state.position[0]+2).toFixed(2)} ${state.position[1].toFixed(2)} ${z.toFixed(2)}${def===10?'':` ${$('support').value} ${$('build-tier').value}`}`);};
$('command-form').onsubmit=e=>{e.preventDefault();act($('command').value.trim());};$('quit').onclick=async()=>{await api('/quit');$('message').textContent='월드를 저장하고 종료합니다.';};$('invite').onclick=async()=>{const i=await api('/info');if(i.invitation){await navigator.clipboard.writeText(i.invitation);$('message').textContent='초대 주소를 복사했습니다.';}else $('message').textContent='방장 모드에서 초대 주소를 만들 수 있습니다.';};
const keys=new Set();document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();$('fire').click();}else if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code)){e.preventDefault();keys.add(e.code);}});document.addEventListener('keyup',e=>keys.delete(e.code));window.onblur=()=>keys.clear();
let steering=0,lastDrive='';setInterval(()=>{if(!state||busy)return;let x=Number(keys.has('KeyW')||keys.has('ArrowUp'))-Number(keys.has('KeyS')||keys.has('ArrowDown')),y=Number(keys.has('KeyA')||keys.has('ArrowLeft'))-Number(keys.has('KeyD')||keys.has('ArrowRight'));if(state.vehicle!=='0:0'){steering=Math.max(-1,Math.min(1,steering+(y?y*.05:-Math.sign(steering)*.05)));const drive=`drive ${state.vehicle} ${Math.abs(x)} ${x?0:1} ${steering.toFixed(2)} ${x<0?0:2}`;if(keys.size||drive!==lastDrive){lastDrive=drive;act(drive);}return;}lastDrive='';steering=0;const len=Math.hypot(x,y);if(len)act(`move ${(state.position[0]+x/len*.45).toFixed(2)} ${(state.position[1]+y/len*.45).toFixed(2)} 0`);},100);
$('map').onclick=async e=>{if(!state)return;const r=e.target.getBoundingClientRect(),x=(e.clientX-r.left)/r.width*900-450,y=300-(e.clientY-r.top)/r.height*600;let yaw=Math.round(Math.atan2(y,x)*65536/(2*Math.PI));if(yaw>32767)yaw-=65536;await act(`aim ${yaw} 0`);};
refresh();setInterval(refresh,250);
